#PBS -N job_nb50_dr5_tf10000_sr001
#PBS -l select=1:ncpus=28:mem=64gb,walltime=06:00:00
#PBS -m abe

module load rust/1.44.0-gcc/8.3.1
module load hdf5/1.10.6-gcc/8.3.1-cuda10_2-mpi

export HDF5_DIR=/software/spackages/linux-centos8-x86_64/gcc-8.3.1/hdf5-1.10.6-p5zs3t6ae54z2csnomsus5gcgvi4rt6t

cd /home/zhongth/rust_projects/binary2d

cargo run --release num_blocks=50 domain_radius=5.0 sink_radius=0.01 tfinal=10000.0 --fold=10000 --outdir=/home/zhongth/rust_projects/binary2d/data_collection/job_dr5_nb50_sr001_tf10000
